version: '3.9'
 
services:

  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    # environment:
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U todo_user -d labo -h db"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
      
    env_file:
      - .env
    networks:
      - database
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build: ./backend
    expose:
      - "8888"
      #- "8000:8888"
    env_file:
      - .env


    networks:
      - web
      - database

  pointsapp:
    build: ./pointsApp
    networks:
      - web
      
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    


networks:
  web:
  database:

volumes:
  postgres:

